services:
    app.doctrine_manager:
        class: AppBundle\Manager\AbstractDoctrineManager
        abstract: true
        arguments:
            - "@=service('doctrine').getManager()"

    app.category_manager:
        class: AppBundle\Manager\CategoryManager
        parent: app.doctrine_manager

    app.task_manager:
        class: AppBundle\Manager\TaskManager
        parent: app.doctrine_manager
