services:
    app.normalizer.category:
        class: AppBundle\Serializer\Normalizer\CategoryNormalizer
        tags:
            - { name: serializer.normalizer }

    app.normalizer.task:
        class: AppBundle\Serializer\Normalizer\TaskNormalizer
        tags:
            - { name: serializer.normalizer }
