fos_rest:
    body_listener: true
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        empty_content: 204
        formats:
            json : true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }

sonata_block:
    default_contexts: [cms]
    profiler:
        enabled: false
        container_types: ~
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title:      Trello
    show_mosaic_button: false
    options:
        title_mode: single_text
        html5_validate: true
        confirm_exit: true

nelmio_api_doc: ~

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: []
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
