# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: "%app.password%"
                        roles: 'ROLE_USER'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: false

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

    access_control:
        - { path: ^/, roles: ROLE_USER }
